# Generated by Django 5.0.2 on 2024-09-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHART', '0003_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
