# Generated by Django 5.0.2 on 2024-09-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHART', '0004_newtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtag',
            name='tag',
            field=models.CharField(max_length=5),
        ),
    ]
