from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('coadmin/', views.coadmin, name='coadmin'),
    path('<str:list_user_id>/user_edit/', views.user_edit, name='user_edit'),
    path('<str:list_user_id>/user_delete/', views.user_delete, name='user_delete'),
    path('adduser/', views.adduser, name='adduser'),
    path('about/', views.about, name='about'),
    path('login/', views.co_login, name='login'),
    path('logout/', views.co_logout, name='logout'),
    path('contact/', views.contact, name='contact'),
    path('jantri/', views.jantri, name='jantri'),
    path('userguide/', views.userguide, name='userguide'),
    path('tools/', views.tools, name='tools'),
    path('delete_alltags/', views.delete_alltags, name='delete_alltags'),
    path('<str:game_result_id>/edit_results/', views.edit_results, name='edit_results'),
    path('<str:game_result_id>/delete_results/', views.delete_results, name='delete_results'),
    path('db20/', views.db20, name='db20'),
    path('db21/', views.db21, name='db21'),
    path('db22/', views.db22, name='db22'),
    path('db23/', views.db23, name='db23'),
    path('sg20/', views.sg20, name='sg20'),
    path('sg21/', views.sg21, name='sg21'),
    path('sg22/', views.sg22, name='sg22'),
    path('sg23/', views.sg23, name='sg23'),
    path('fb20/', views.fb20, name='fb20'),
    path('fb21/', views.fb21, name='fb21'),
    path('fb22/', views.fb22, name='fb22'),
    path('fb23/', views.fb23, name='fb23'),
    path('fz20/', views.fz20, name='fz20'),
    path('fz21/', views.fz21, name='fz21'),
    path('fz22/', views.fz22, name='fz22'),
    path('fz23/', views.fz23, name='fz23'),
    path('gb20/', views.gb20, name='gb20'),
    path('gb21/', views.gb21, name='gb21'),
    path('gb22/', views.gb22, name='gb22'),
    path('gb23/', views.gb23, name='gb23'),
    path('lb20/', views.lb20, name='lb20'),
    path('lb21/', views.lb21, name='lb21'),
    path('lb22/', views.lb22, name='lb22'),
    path('lb23/', views.lb23, name='lb23'),
    path('gl20/', views.gl20, name='gl20'),
    path('gl21/', views.gl21, name='gl21'),
    path('gl22/', views.gl22, name='gl22'),
    path('gl23/', views.gl23, name='gl23'),
    path('ds20/', views.ds20, name='ds20'),
    path('ds21/', views.ds21, name='ds21'),
    path('ds22/', views.ds22, name='ds22'),
    path('ds23/', views.ds23, name='ds23'),

    path('january2024/', views.january, name='january2024'),
    path('february2024/', views.february, name='february2024'),
    path('march2024/', views.march, name='march2024'),
    path('april2024/', views.april, name='april2024'),
    path('may2024/', views.may, name='may2024'),
    path('june2024/', views.june, name='june2024'),
    path('july2024/', views.july, name='july2024'),
    path('august2024/', views.august, name='august2024'),
    path('september2024/', views.september, name='september2024'),
]
